### ISSUE TITLE
Inquire about the programming language of the script 

### ISSUE THREAD

**Issue by MrVinegar** [chrisreyn/Tap-Titans-2-Progress-Bot#11]
Hey Chrisreyn,

First of all thank you very much for your contribution, I’ve had a lot of fun making modifications to the script according to my personal needs. Second of all I just want to know if you can share the programming language y’all used to write this script since I think it’s fascinating to be able to do things like this because I wanna be a computer Science major in college. Last but not least, you guys are awesome!!!

**Comment by chrisreyn** [comment]
this isn't any concrete coding language. It is similar to C, but less strict. I wouldn't recommend practicing coding using HiroMacro especially since running these codes have errors themselves, unlike the more structured languages. 

though if you must learn a bit more on HiroMacro for your script needs: http://prohiro.com/?page_id=399

here are nice places to start out with C++
https://www.hackerrank.com/domains/cpp/cpp-introduction
http://codingbat.com/java
https://www.w3resource.com/cpp-exercises/basic/index.php

enjoy coding!
