### ISSUE TITLE
Skills maxing

### ISSUE THREAD

**Issue by core66** [chrisreyn/Tap-Titans-2-Progress-Bot#14]
Hi Guys,

unfortunately, I can not get the script to maximize skills at level 25. it will only be maximized for the first time after the Prestige, but then not anymore. Only the tab is opened, scrolled and closed again. So the Skills stay at level 19 - 20. and when a skill is active he didnt upgrade.

Can you help me?

**Comment by chrisreyn** [comment]
```
var #runActionsEveryXSeconds 94
// recommended equal to total SC+ED+DShift duration minus ~6 or 7 seconds
// ^esp if you cant level SC in the first run
```

so that when `:runActions` runs, SC (or your other skills) is done and script can level them up. script is currently set to not level up when skill is running so you dont waste mana

also, make sure you have a higher value for `var #stopLevelSkillMins`. it wont level up skills past the specified minutes

see `:lvlTopHero` for other conditions

**Comment by core66** [comment]
thank you, but i want that the Script is upgrading the skills it doesnt matter the skill is active or not.

is this possible?

**Comment by chrisreyn** [comment]
```
:lvlSkill
	if #minutes >= #maxSkillsAtXMinutes and #unlocked < 8 and #skillCheckStepper <= 5
		touchPress 0 459 755
		sleep 300
		#time = #time + 300
		#unlocked = #unlocked + 1
	endif
	
	#time = #time + 100
	getRGB #colorRed #colorGreen #colorBlue 459 755
	if #colorBlue <= -45
		sleep 10
		#time = #time + 10
		goto :endLvlSkill
	elseif #justUnlockSkills == 0
		goto :maxSkill
```

change `getRGB #colorRed #colorGreen #colorBlue 459 755` to `#colorBlue = 0`
