### ISSUE TITLE
Attack CQ

### ISSUE THREAD

**Issue by Gufis22** [chrisreyn/Tap-Titans-2-Progress-Bot#9]
Hello, i was wondering if anyone had a working script for attacking CQ's with diamonds with limited attacks. For example only using free + 5 diamond attacks instead of just going all out on diamonds till the boss dies.

**Comment by Vhivi** [comment]
Hello,

Set the correct parameters for you.

`// ---------- Actions ---------- [ ClanQuest ]
var #enableClanQuest 1

//clan boss with max possible hits
var #clanQuestRunsPerReadyUp 1
// 1 = (default) attack every ready up once for free
// 2-99 = spend dias for more attacks`

**Comment by Gufis22** [comment]
That's not what i'm talking about. If you set it to 1 it only does free attacks, but if you set it to 2 or more it goes all out and spends all of your diamonds. I want an option to use the free attack + the one that costs 5 diamonds.

**Comment by Vhivi** [comment]
Heelo,

Sorry, I do not use this option but I understand the question and according to the code the parameter "var #clanQuestRunsPerReadyUp" set to 2 can do exactly what you want, a free attack + a diamond attack.

However, it is repeated until your boss has fallen so yes you eat diamonds. The code just checks colors to see if it can click the button, it does not check if you have already spent diamonds on the previous attack since it does not even know if it's the same boss that you're in to beat.
