### ISSUE TITLE
Doesnt upgrade tap damage need help!

### ISSUE THREAD

**Issue by limburgerrr** [chrisreyn/Tap-Titans-2-Progress-Bot#90]
Hello,

when i start the bot/script it only does 1 time upgrade my tap damage hero and the other skills and nothing else only when prestige?

ill attach my TXT 

if somebody please can have a look ill did search the forum over and over again but i cant find the solution?

Greetttzzz
[weeraaassss.txt](https://github.com/chrisreyn/Tap-Titans-2-Progress-Bot/files/3185829/weeraaassss.txt)

**Comment by chrisreyn** [comment]
yea, that's how the script is set currently. it assumes you're high level enough to buy all level 25 skills and run all the skills from the get go. it's been a while since i last needed frequent sword master levelling so i dont remember that part of the code anymore tbh. i have yet to make it more flexible on that part, but i do the code editing for my personal gain and sharing it is just a bonus so it's on a low priority. sorry mate

just to give context, i started using this code with high mana siphon i think 16 and eventually, im now at low mana siphon (or none really)  so ive adjusted it so and barely made it new player friendly 😬

**Comment by limburgerrr** [comment]
anyway thankyou for replay!:D
